replication: true
replicas: 1
serviceType: NodePort


serviceAccounts:
  spark:
    # -- Create a service account for spark apps
    create: true
    # -- Optional name for the spark service account
    name: "spark"
    # -- Optional annotations for the spark service account
    annotations: {}
  sparkoperator:
    # -- Create a service account for the operator
    create: true
    # -- Optional name for the operator service account
    name: "spark-operator"
    # -- Optional annotations for the operator service account
    annotations: {}
